[workspace]

members = [
    'net/rtmpserver'
]

# Only plugins without external dependencies
default-members = [
    'net/rtmpserver'
]


[profile.release]
lto = true
opt-level = 3
debug = true
panic = 'unwind'

[profile.dev]
opt-level = 1

